In [5]:
# The first step
from semopy import Model
mod = """ eta1 ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + x20
          eta1 is ordinal
          x1 is ordinal
          x2 is ordinal
          x3 is ordinal
          x4 is ordinal
          x5 is ordinal
          x6 is ordinal
          x7 is ordinal
          x8 is ordinal
          x9 is ordinal
          x10 is ordinal
          x11 is ordinal
          x12 is ordinal
          x13 is ordinal
          x14 is ordinal
          x15 is ordinal
          x16 is ordinal
          x17 is ordinal
          x18 is ordinal
          x19 is ordinal
          x20 is ordinal
      """
model = Model(mod)

In [16]:
# The first step
from semopy import Model
mod = """ eta1 ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + x20
          eta1 is ordinal
      """
model = Model(mod)

In [17]:
# The second step
from pandas import read_csv
data = read_csv("D:\\Study\\\DataScience\\\FlightDelay\\ORDDiscrete_15minBoundary_2008-SEM.csv")
model.load_dataset(data)

In [18]:
from semopy import Optimizer
opt = Optimizer(model)
objective_function_value = opt.optimize()

In [19]:
from semopy.inspector import inspect
inspect(opt)

E:\Software\AnacondaForPython\installation\Anaconda2\envs\nlu\lib\site-packages\semopy\stats.py:379: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt((chisqr / dof - 1) / (opt.profiles.shape[0] - 1))

    lval  op  rval     Value        SE     Z-score       P-value
0   eta1   ~    x1 -0.079552  0.001394  -57.055793  0.000000e+00
1   eta1   ~   x10 -0.005525  0.001021   -5.412977  6.198541e-08
2   eta1   ~   x11 -0.532612  0.004000 -133.164770  0.000000e+00
3   eta1   ~   x12  0.014327  0.001134   12.633356  0.000000e+00
4   eta1   ~   x13  0.107011  0.001175   91.083506  0.000000e+00
5   eta1   ~   x14 -0.025024  0.001072  -23.335189  0.000000e+00
6   eta1   ~   x15  0.011399  0.001096   10.400984  0.000000e+00
7   eta1   ~   x16 -0.003595  0.001101   -3.266263  1.089771e-03
8   eta1   ~   x17  0.012728  0.001923    6.618618  3.625744e-11
9   eta1   ~   x18 -0.008101  0.001153   -7.026399  2.119416e-12
10  eta1   ~   x19  0.016658  0.001290   12.917110  0.000000e+00
11  eta1   ~    x2  0.621225  0.003841  161.749364  0.000000e+00
12  eta1   ~   x20  0.000533  0.001139    0.467496  6.401454e-01
13  eta1   ~    x3  0.048694  0.001953   24.928473  0.000000e+00
14  eta1   ~    x4 -0.018210  0.001178  -15.455086  0.000000e+00
15  eta1   ~    x5  0.513200  0.001262  406.762972  0.000000e+00
16  eta1   ~    x6  0.045753  0.002066   22.142659  0.000000e+00
17  eta1   ~    x7  0.190641  0.001616  117.953206  0.000000e+00
18  eta1   ~    x8  0.003524  0.001088    3.239339  1.198071e-03
19  eta1   ~    x9  0.010393  0.001030   10.088072  0.000000e+00
20  eta1  ~~  eta1  0.308542  0.000801  385.114268  0.000000e+00

In [2]:
from random import seed
from random import randint
from random import random
import pandas as pd

seed(1)

vals = []

for iVal in range(10000):
    x1 = randint(0,1000)
    x2 = randint(0,1000)
    x3 = randint(0,1000)
    x4 = randint(0,1000)
    x5 = randint(0,1000)
    x6 = randint(0,1000)
    x7 = randint(0,1000)
    err = random()
    eta1 = 1 * x1 + 2 * x2 + 3 * x3 + 2 * x4 + 5 * x5 + 4 * x6 + err
    
    vals.append([x1, x2, x3, x4, x5, x6, x7, eta1])
    

df = pd.DataFrame(vals, columns = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'eta1'])

In [4]:
model.load_dataset(df)
from semopy import Optimizer
opt = Optimizer(model)
objective_function_value = opt.optimize()

In [5]:
from semopy.inspector import inspect
inspect(opt)

E:\Software\AnacondaForPython\installation\Anaconda2\envs\nlu\lib\site-packages\semopy\stats.py:379: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt((chisqr / dof - 1) / (opt.profiles.shape[0] - 1))

   lval  op  rval         Value            SE    Z-score   P-value
0  eta1   ~    x1  1.000007e+00      0.054749  18.265388  0.000000
1  eta1   ~    x2  1.999991e+00      0.054729  36.543522  0.000000
2  eta1   ~    x3  2.999981e+00      0.054759  54.785141  0.000000
3  eta1   ~    x4  2.000005e+00      0.054595  36.633475  0.000000
4  eta1   ~    x5  5.000014e+00      0.054634  91.518395  0.000000
5  eta1   ~    x6  4.000003e+00      0.054591  73.272824  0.000000
6  eta1   ~    x7  2.743191e-07      0.054864   0.000005  0.999996
7  eta1  ~~  eta1  2.502666e+06  35393.044851  70.710678  0.000000